### ISSUE TITLE
exception in `avoid_shadowing_type_parameters` when parsing invalid code

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1447]
Here's the source that triggered it:

```dart
typedef Predicate = bool <E>(E element);
```

Analyzer Feedback from IntelliJ

## Version information

- `IDEA 191.5109.14`
- `2.2.0-edge.6b5424a7e7a9b92d70c35baca9f72db8471b55e4`
- `IU-191.5109.14, JRE 1.8.0_202-release-1483-b4x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.6b5424a7e7a9b92d70c35baca9f72db8471b55e4, server version 1.23.0, error: Exception while using a AvoidShadowingTypeParameters to visit a GenericTypeAliasImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'typeParameters' was called on null.
Receiver: null
Tried calling: typeParameters
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      _Visitor.visitGenericTypeAlias (file:///Users/pquitslund/src/repos/dart/sdk/third_party/pkg/linter/lib/src/rules/avoid_shadowing_type_parameters.dart:65:27)
#2      GenericTypeAliasImpl.accept (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/ast/ast.dart:6304:20)
#3      LinterVisitor._runSubscriptions (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/lint/linter_visitor.dart:731:14)
#4      LinterVisitor.visitGenericTypeAlias (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/lint/linter_visitor.dart:353:5)
#5      GenericTypeAliasImpl.accept (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/ast/ast.dart:6304:20)
#6      NodeListImpl.accept (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/ast/ast.dart:8948:20)
#7      CompilationUnitImpl.visitChildren (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/ast/ast.dart:2446:21)
#8      RecursiveAstVisitor.visitCompilationUnit (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/dart/ast/visitor.dart:764:10)
#9      LinterVisitor.visitCompilationUnit (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/lint/linter_visitor.dart:126:11)
#10     CompilationUnitImpl.accept (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/ast/ast.dart:2439:49)
#11     LibraryAnalyzer._computeLints (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/analysis/library_analyzer.dart:316:10)
#12     LibraryAnalyzer.analyzeSync.<anonymous closure> (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/analysis/library_analyzer.dart:168:11)
#13     _PerformanceTagImpl.makeCurrentWhile (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/generated/utilities_general.dart:258:15)
#14     LibraryAnalyzer.analyzeSync (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/analysis/library_analyzer.dart:163:35)
#15     LibraryAnalyzer.analyze.<anonymous closure> (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/analysis/library_analyzer.dart:98:14)
#16     _PerformanceTagImpl.makeCurrentWhile (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/generated/utilities_general.dart:258:15)
#17     LibraryAnalyzer.analyze (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/analysis/library_analyzer.dart:97:43)
#18     AnalysisDriver._computeAnalysisResult.<anonymous closure> (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/analysis/driver.dart:1438:63)
#19     PerformanceLog.run (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/analysis/performance_logger.dart:34:15)
#20     AnalysisDriver._computeAnalysisResult (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/analysis/driver.dart:1416:20)
#21     AnalysisDriver.performWork (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/analysis/driver.dart:1088:33)
<asynchronous suspension>
#22     AnalysisDriverScheduler._run (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#23     AnalysisDriverScheduler.start (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/lib/src/dart/analysis/driver.dart:2075:5)
#24     new AnalysisServer (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analysis_server/lib/src/analysis_server.dart:213:29)
#25     SocketServer.createAnalysisServer (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analysis_server/lib/src/socket_server.dart:86:26)
#26     StdioAnalysisServer.serveStdio (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analysis_server/lib/src/server/stdio_server.dart:37:18)
#27     Driver.startAnalysisServer.<anonymous closure> (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analysis_server/lib/src/server/driver.dart:511:21)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     Driver._captureExceptions (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analysis_server/lib/src/server/driver.dart:590:12)
#33     Driver.startAnalysisServer (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analysis_server/lib/src/server/driver.dart:509:7)
#34     Driver.start (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analysis_server/lib/src/server/driver.dart:412:7)
#35     main (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analysis_server/bin/server.dart:12:11)
#36     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#37     main (file:///Users/pquitslund/src/repos/dart/sdk/pkg/analysis_server/bin/server.dart:10:10)
#38     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#39     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

**Comment by bwilkerson** [comment]
We definitely need to guard against the NPE in the linter.

The bigger issue, in my mind, is the way analyzer is recovering in this situation. I've added a test for this case so that we don't forget it (https://dart-review.googlesource.com/c/sdk/+/94141).

**Comment by pq** [comment]
Great.  Thanks Brian!
