### ISSUE TITLE
'ExtensionElementImpl' is not a subtype of type 'ClassElement' in type cast

### ISSUE THREAD

**Issue by scheglov** [dart-lang/linter#1741]
Analyzer Feedback from IntelliJ

Obviously, not a valid Dart code, but should not crash :-)

## Version information

- `IDEA 193.SNAPSHOT`
- `2.6.0-edge.87d795c177b3646e7dff1ee7d09a47b00e8d3a17`
- `IC-193.SNAPSHOT, JRE 1.8.0_221-b11x64 Oracle Corporation, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.87d795c177b3646e7dff1ee7d09a47b00e8d3a17, server version 1.27.3, error: Exception while using a OverriddenFields to visit a FieldDeclarationImpl in ExtensionDeclarationImpl in CompilationUnitImpl
type 'ExtensionElementImpl' is not a subtype of type 'ClassElement' in type cast
#0      _Visitor._getOverriddenMember (package:linter/src/rules/overridden_fields.dart:150:50)
#1      _Visitor.visitFieldDeclaration.<anonymous closure> (package:linter/src/rules/overridden_fields.dart:127:11)
#2      ListMixin.forEach (dart:collection/list.dart:63:13)
#3      _Visitor.visitFieldDeclaration (package:linter/src/rules/overridden_fields.dart:125:27)
#4      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4095:49)
#5      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:725:14)
#6      LinterVisitor.visitFieldDeclaration (package:analyzer/src/lint/linter_visitor.dart:257:5)
#7      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4095:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#9      ExtensionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3936:14)
#10     RecursiveAstVisitor.visitExtensionDeclaration (package:analyzer/dart/ast/visitor.dart:845:10)
#11     LinterVisitor.visitExtensionDeclaration (package:analyzer/src/lint/linter_visitor.dart:246:11)
#12     ExtensionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3928:49)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#14     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#15     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#16     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:126:11)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#18     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:342:10)
#19     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:195:11)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:190:35)
#22     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:113:14)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:112:43)
#25     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1256:63)
#26     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#27     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1232:20)
#28     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:924:33)
<asynchronous suspension>
#29     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#30     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#31     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#32     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#33     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#34     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:568:21)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:685:12)
#40     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:566:7)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:467:9)
#42     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#43     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:462:43)
#44     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#45     new Future.sync (dart:async/future.dart:224:31)
#46     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#47     _rootRun (dart:async/zone.dart:1124:13)
#48     _CustomZone.run (dart:async/zone.dart:1021:19)
#49     _runZoned (dart:async/zone.dart:1516:10)
#50     runZoned (dart:async/zone.dart:1463:12)
#51     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#52     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.d...
```

For additional log information, please append the contents of
file:///private/var/folders/5_/801pkmkn457fzp_twzmc2g88003ky_/T/report2.txt.

```dart
class A {
  const A(Object value);
}
class C {
  static int f;
    metadata
      Annotation
        arguments: ArgumentList
          arguments
            SimpleIdentifier
              staticElement: self::C::m
              staticType: void Function()
              token: m
        element: self::A::•
        name: SimpleIdentifier
          staticElement: self::A
          staticType: Type
          token: A
  static void m() {}
}
mixin M on Object {
  static int f;
    metadata
      Annotation
        arguments: ArgumentList
          arguments
            SimpleIdentifier
              staticElement: self::M::m
              staticType: void Function()
              token: m
        element: self::A::•
        name: SimpleIdentifier
          staticElement: self::A
          staticType: Type
          token: A
  static void m() {}
}
extension E on int {
  static int f;
    metadata
      Annotation
        arguments: ArgumentList
          arguments
            SimpleIdentifier
              staticElement: self::E::m
              staticType: void Function()
              token: m
        element: self::A::•
        name: SimpleIdentifier
          staticElement: self::A
          staticType: Type
          token: A
  static void m() {}
}
```

**Comment by pq** [comment]
Thanks for the report!

**Comment by pq** [comment]
Makes me think we should really be fuzzing for these...

If we aren't already?

/cc @MichaelRFairhurst
