### ISSUE TITLE
Exception thrown in master 6d3bdf0

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/linter#228]
I tried running the analysis in dart-lang/sdk and dart-lang/markdown and the following exception was thrown in both cases.

```
An error occurred while linting
  Please report it at: github.com/dart-lang/linter/issues
The null object does not have a method 'filter'.

NoSuchMethodError: method not found: 'filter'
Receiver: null
Arguments: [Instance of 'AnalysisError']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _maxSeverity.<anonymous closure> (file:///home/alexeieleusis/development/dart/linter/bin/linter.dart:181:45)
#3      WhereIterator.moveNext (dart:_internal/iterable.dart:439)
#4      Iterable.forEach (dart:core/iterable.dart:218)
#5      _maxSeverity (file:///home/alexeieleusis/development/dart/linter/bin/linter.dart:182:10)
#6      runLinter (file:///home/alexeieleusis/development/dart/linter/bin/linter.dart:155:18)
#7      main (file:///home/alexeieleusis/development/dart/linter/bin/linter.dart:18:3)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by pq** [comment]
Ouch.  Reproed and fixing.  Thanks!

**Comment by alexeieleusis** [comment]
Thank you!

**Comment by pq** [comment]
👍 

https://codereview.chromium.org/1918933002/

**Comment by alexeieleusis** [comment]
thank you!

**Comment by pq** [comment]
And thanks for catching it!
