### ISSUE TITLE
Exception thrown in master c32863d52d592a1066be639f5e40a3c0b7241bbf

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/linter#231]
```
in ~/development/dart/dev_compiler@edd890ebedbefa862408032ad4b6418d0c409428
$ dart ~/development/dart/linter/bin/linter.dart . > linter.txt                                                                               
An error occurred while linting
  Please report it at: github.com/dart-lang/linter/issues
The null object does not have a getter 'length'.

NoSuchMethodError: method not found: 'length'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      DetailedReporter.writeLint (package:linter/src/formatter.dart:76:54)
#3      SimpleFormatter._writeLint (package:linter/src/formatter.dart:276:5)
#4      SimpleFormatter.writeLints.<anonymous closure>.<anonymous closure> (package:linter/src/formatter.dart:212:15)
#5      List.forEach (dart:core-patch/growable_array.dart:254)
#6      SimpleFormatter.writeLints.<anonymous closure> (package:linter/src/formatter.dart:206:68)
#7      List.forEach (dart:core-patch/growable_array.dart:254)
#8      SimpleFormatter.writeLints (package:linter/src/formatter.dart:206:12)
#9      SimpleFormatter.write (package:linter/src/formatter.dart:153:5)
#10     runLinter (file:///usr/local/google/home/alexeidiaz/development/dart/linter/bin/linter.dart:168:14)
#11     main (file:///usr/local/google/home/alexeidiaz/development/dart/linter/bin/linter.dart:18:3)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by pq** [comment]
Thanks!

Is this reproducible?  Maybe an issue with `getLineContents`?

**Comment by alexeieleusis** [comment]
I now get a different error

linter@ecfaed3ea52ea2b5a7d9e0a7db94cf1f92208280
devcompiler@edd890ebedbefa862408032ad4b6418d0c409428 and
devcompiler@4d27e3f409afaec75a9501eccbe4e52c5ace999f

```
~/development/dart/dev_compiler$ dart ~/development/dart/linter/bin/linter.dart .
Task failed: GenerateLintsTask for source /home/alexeieleusis/development/dart/dev_compiler/test/codegen/language/issue_1751477_lib2.dart
An error occurred while linting
  Please report it at: github.com/dart-lang/linter/issues
AnalysisException: Cannot compute DART_ERRORS for /home/alexeieleusis/development/dart/dev_compiler/test/codegen/language/issue_1751477_lib2.dart
Caused by Unexpected exception while performing GenerateLintsTask for source /home/alexeieleusis/development/dart/dev_compiler/test/codegen/language/issue_1751477_lib2.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276:10)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:18)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:672:14)
#5      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:620:12)
#6      AnalysisDriver.analyze (package:linter/src/analysis.dart:147:15)
#7      DartLinter.lintFiles (package:linter/src/linter.dart:68:34)
#8      runLinter (file:///home/alexeieleusis/development/dart/linter/bin/linter.dart:151:45)
#9      main (file:///home/alexeieleusis/development/dart/linter/bin/linter.dart:18:3)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'source'.

NoSuchMethodError: method not found: 'source'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      Visitor.visitLibraryDirective (package:linter/src/rules/package_prefixed_library_names.dart:89:34)
#3      DelegatingAstVisitor.visitLibraryDirective.<anonymous closure> (package:analyzer/dart/ast/visitor.dart:562:47)
#4      List.forEach (dart:core-patch/growable_array.dart:254)
#5      DelegatingAstVisitor.visitLibraryDirective (package:analyzer/dart/ast/visitor.dart:562:16)
#6      LibraryDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:6632:15)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7671:20)
#8      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2430:19)
#9      DelegatingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:252:10)
#10     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2424:15)
#11     GenerateLintsTask.internalPerform (package:analyzer/src/task/dart.dart:2836:10)
#12     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329:9)
#13     AnalysisTask.perform (package:analyzer/task/model.dart:229:7)
#14     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276:10)
#15     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:18)
#16     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:672:14)
#17     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:620:12)
#18     AnalysisDriver.analyze (package:linter/src/analysis.dart:147:15)
#19     DartLinter.lintFiles (package:linter/src/linter.dart:68:34)
#20     runLinter (file:///home/alexeieleusis/development/dart/linter/bin/linter.dart:151:45)
#21     main (file:///home/alexeieleusis/development/dart/linter/bin/linter.dart:18:3)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:676:7)
#1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:620:12)
#2      AnalysisDriver.analyze (package:linter/src/analysis.dart:147:15)
#3      DartLinter.lintFiles (package:linter/src/linter.dart:68:34)
#4      runLinter (file:///home/alexeieleusis/development/dart/linter/bin/linter.dart:151:45)
#5      main (file:///home/alexeieleusis/development/dart/linter/bin/linter.dart:18:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by alexeieleusis** [comment]
The code where the error occurs is quite artificial and different from the original error report, closing this. We can open a new one if needed.
