### ISSUE TITLE
iterable_contains_unrelated_type crashes when run on Flutter repo

### ISSUE THREAD

**Issue by Hixie** [dart-lang/linter#245]
If I enable `iterable_contains_unrelated_type` in `flutter_analysis_options`, then `flutter analyze` crashes with:
```
NoSuchMethodError: method not found: 'element'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _Visitor.visitMethodInvocation (package:linter/src/rules/iterable_contains_unrelated_type.dart:155)
#3      DelegatingAstVisitor.visitMethodInvocation.<anonymous closure> (package:analyzer/dart/ast/visitor.dart:604)
#4      List.forEach (dart:core-patch/growable_array.dart:254)
#5      DelegatingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:604)
#6      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7303)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682)
#8      ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:423)
#9      DelegatingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140)
#10     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:419)
#11     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7310)
#12     DelegatingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:605)
#13     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7303)
#14     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4150)
#15     DelegatingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:383)
#16     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4146)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682)
#18     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1278)
#19     DelegatingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:182)
#20     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1274)
#21     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1222)
#22     DelegatingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:189)
#23     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1218)
#24     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5228)
#25     DelegatingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:447)
#26     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5222)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682)
#28     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:423)
#29     DelegatingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140)
#30     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:419)
#31     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7310)
#32     DelegatingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:605)
#33     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7303)
#34     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4150)
#35     DelegatingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:383)
#36     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4146)
#37     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682)
#38     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1278)
#39     DelegatingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:182)
#40     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1274)
#41     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1222)
#42     DelegatingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:189)
#43     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1218)
#44     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5228)
#45     DelegatingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:447)
#46     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5222)
#47     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682)
#48     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:423)
#49     DelegatingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140)
#50     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:419)
#51     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7310)
#52     DelegatingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:605)
#53     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7303)
#54     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4150)
#55     DelegatingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:383)
#56     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4146)
#57     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682)
#58     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1278)
#59     DelegatingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:182)
#60     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1274)
#61     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1222)
#62     DelegatingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:189)
#63     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1218)
#64     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5228)
#65     DelegatingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:447)
...
```

**Comment by pq** [comment]
On it.  Thanks!
