### ISSUE TITLE
NSME when file contents cannot be read.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#260]
```
NoSuchMethodError: method not found: 'length'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      DetailedReporter.writeLint (package:linter/src/formatter.dart:76:54)
#3      SimpleFormatter._writeLint (package:linter/src/formatter.dart:276:5)
#4      SimpleFormatter.writeLints.<anonymous closure>.<anonymous closure> (package:linter/src/formatter.dart:212:15)
#5      List.forEach (dart:core-patch/growable_array.dart:254)
#6      SimpleFormatter.writeLints.<anonymous closure> (package:linter/src/formatter.dart:206:68)
#7      List.forEach (dart:core-patch/growable_array.dart:254)
#8      SimpleFormatter.writeLints (package:linter/src/formatter.dart:206:12)
#9      SimpleFormatter.write (package:linter/src/formatter.dart:153:5)
#10     runLinter (file:///Users/pquitslund/src/git/clones/linter/bin/linter.dart:172:14)
#11     main (file:///Users/pquitslund/src/git/clones/linter/bin/linter.dart:18:3)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by pq** [comment]
Fix [in flight](https://codereview.chromium.org/2061383003/).

Once landed, above message will look like:

```
An error occurred while linting
  Please report it at: github.com/dart-lang/linter/issues
Bad state: Unable to get contents for line: line index (262), outside of file line range (262)
#0      getLineContents (package:linter/src/formatter.dart:31:3)
#1      DetailedReporter.writeLint (package:linter/src/formatter.dart:77:22)
#2      SimpleFormatter._writeLint (package:linter/src/formatter.dart:281:5)
#3      SimpleFormatter.writeLints.<anonymous closure>.<anonymous closure> (package:linter/src/formatter.dart:217:15)
...
```
