### ISSUE TITLE
enhanced enums support for `annotate_overrides`

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3093]

**Comment by pq** [comment]
#3186 adds tests but with the latest published analyzer the `test_ok` case is erroring:

```
package:analyzer/src/dart/analysis/driver.dart 1476:9             AnalysisDriver._computeAnalysisResult.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 32:15  PerformanceLog.run
package:analyzer/src/dart/analysis/driver.dart 1424:20            AnalysisDriver._computeAnalysisResult
package:analyzer/src/dart/analysis/driver.dart 1050:22            AnalysisDriver.performWork
package:analyzer/src/dart/analysis/driver.dart 2127:24            AnalysisDriverScheduler._run

Null check operator used on a null value
#0      AnnotationResolver._resolve (package:analyzer/src/dart/resolver/annotation_resolver.dart:309:43)
#1      AnnotationResolver.resolve (package:analyzer/src/dart/resolver/annotation_resolver.dart:34:5)
#2      ResolverVisitor.visitAnnotation (package:analyzer/src/generated/resolver.dart:1074:25)
#3      AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:297:50)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7813:20)
#5      AnnotatedNodeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:144:17)
#6      MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7181:11)
#7      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1931:10)
#8      UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3561:56)
#9      ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:1834:13)
#10     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7177:50)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7813:20)
#12     EnumDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3415:14)
#13     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1931:10)
#14     UnifyingAstVisitor.visitEnumDeclaration (package:analyzer/dart/ast/visitor.dart:3419:52)
#15     ResolverVisitor.visitEnumDeclaration (package:analyzer/src/generated/resolver.dart:1502:13)
#16     EnumDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3405:50)
#17     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:1314:23)
#18     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2098:50)
#19     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:779:10)
#20     LibraryAnalyzer._parseAndResolve.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:597:7)
#21     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:574:13)
#22     LibraryAnalyzer._parseAndResolve (package:analyzer/src/dart/analysis/library_analyzer.dart:596:11)
#23     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:105:17)
#24     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1447:11)
#25     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#26     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1424:20)
#27     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1050:22)
#28     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2127:24)
<asynchronous suspension>
```


@scheglov, FWIW, this fails for different reasons against tip of tree:


```
Found but did not expect:
  HintCode.OVERRIDE_ON_NON_OVERRIDING_GETTER [40, 8, The getter doesn't override an inherited getter.]
  HintCode.OVERRIDE_ON_NON_OVERRIDING_METHOD [76, 8, The method doesn't override an inherited method.]

```

Here's the test source:

```dart
  test_ok() async {
    await assertNoDiagnostics(r'''
enum A {
  a,b,c;
  @override
  int get hashCode => 0;
  @override
  String toString() => '';
}
''');
  }
```

**Comment by pq** [comment]
RE: `HintCode.OVERRIDE_ON_NON_OVERRIDING_METHOD`, see also #3188.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/234221
