### ISSUE TITLE
travis script is failing

### ISSUE THREAD

**Issue by JPaulsen** [dart-lang/linter#421]
Running the script at head 0e0e2ef2007810a71fc7619b473a6f125bb372ae fails with the following:

```
± |dart_import_first {1} S:4 U:5 ✗| → ./tool/travis.sh 
Analyzing [bin/linter.dart, test/all.dart]...
Unhandled exception:
NoSuchMethodError: The getter 'pubExecutable' was called on null.
Receiver: null
Tried calling: pubExecutable
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      PubPackageMapProvider._runPubListDefault (package:analyzer/source/pub_package_map_provider.dart:173)
#3      PubPackageMapProvider.computePackageMap (package:analyzer/source/pub_package_map_provider.dart:74)
#4      Driver._chooseUriResolutionPolicy (package:analyzer_cli/src/driver.dart:408)
#5      Driver._createAnalysisContext (package:analyzer_cli/src/driver.dart:539)
#6      Driver._analyzeAllImpl.<_analyzeAllImpl_async_body> (package:analyzer_cli/src/driver.dart:184)
#7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by pq** [comment]
Hmmm.  Things look OK now?  Can we close?

**Comment by JPaulsen** [comment]
This happens when running locally in a Goobuntu machine, is it supported?

**Comment by pq** [comment]
Not sure about local runs of travis builds.

@devoncarew ?

**Comment by devoncarew** [comment]
@JPaulsen, what verison of the sdk are you using?

> PubPackageMapProvider._runPubListDefault

If this is a recent sdk, we probably should not be invoking the pub process.

**Comment by JPaulsen** [comment]
@devoncarew 

```
$dart --version
Dart VM version: 1.22.0-dev.10.6+google3-v1.22.0.dev.10.6 (google3) on "linux_x64"
```

**Comment by pq** [comment]
Any update on this one?

@JPaulsen, @devoncarew : can we close?
