### ISSUE TITLE
prefer_const_literals_to_create_immutables: Exception while using a Visitor to visit a ListLiteralImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in TryStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl

### ISSUE THREAD

**Issue by DanTup** [dart-lang/linter#920]
Not sure if this is analyzer or linter issue, but since the top of the call stack shows `prefer_const_literals_to_create_immutables.dart` I figured I'd start here.

I was editing `gradle.dart` in `flutter_tools` and commenting out the try/catch inside the `_readGradleProject` method.

Exception from analysis server (running from VSCode / Dart Code)

### Versions

- Dart SDK 2.0.0-edge.00225dedfead37ae670bddca9b15509401844b3b
- Flutter SDK 0.2.2-pre.24
- Visual Studio Code 1.21.0
- Dart Code 2.11.0-dev

### Analyzer Info

The analyzer was launched using the arguments:

```text
M:\Coding\Applications\Google\dart-sdk\sdk\pkg\analysis_server\bin\server.dart
--client-id=Dart-Code.dart-code
--client-version=2.11.0-dev
```

### Exception

Exception while using a Visitor to visit a ListLiteralImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in TryStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl

```text
NoSuchMethodError: Class 'DynamicTypeImpl' has no instance getter 'superclass'.
Receiver: Instance of 'DynamicTypeImpl'
Tried calling: superclass
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      Visitor._getSelfAndInheritedTypes (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:132:25)
#2      _SyncIterator.moveNext (dart:core-patch/dart:core/core_patch.dart:153)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#4      ExpandIterator.moveNext (dart:_internal/iterable.dart:477)
#5      MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#6      Iterable.any (dart:core/iterable.dart:402)
#7      Visitor._hasImmutableAnnotation (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:125:40)
#8      Visitor._visitTypedLiteral (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:93:9)
#9      Visitor.visitListLiteral (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:73:46)
#10     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:7342:49)
#11     ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2757:14)
#12     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#13     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2755:15)
#14     UnifyingAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:3097:43)
#15     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:7342:49)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8242:20)
#17     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:433:16)
#18     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762:10)
#19     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898:45)
#20     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:429:49)
#21     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6641:20)
#22     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762:10)
#23     UnifyingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:3069:7)
#24     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6567:15)
#25     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9335:18)
#26     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762:10)
#27     UnifyingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:3159:51)
#28     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:9331:49)
#29     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8242:20)
#30     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1351:17)
#31     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762:10)
#32     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919:31)
#33     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1347:49)
#34     TryStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10706:12)
#35     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762:10)
#36     UnifyingAstVisitor.visitTryStatement (package:analyzer/dart/ast/visitor.dart:3209:45)
#37     TryStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10702:49)
#38     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8242:20)
#39     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1351:17)
#40     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762:10)
#41     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919:31)
#42     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1347:49)
#43     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1296:13)
#44     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762:10)
#45     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922:55)
#46     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1292:49)
#47     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5430:12)
#48     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762:10)
#49     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033:57)
#50     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5424:49)
#51     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5275:26)
#52     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762:10)
#53     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026:59)
#54     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5268:49)
#55     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8242:20)
#56     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2507:21)
#57     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762:10)
#58     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949:51)
#59     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2500:49)
#60     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:371:10)
#61     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:163:13)
#62     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
#63     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:17)
#64     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:207:15)
#65     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:161:37)
#66     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101:16)
<asynchronous suspension>
#67     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217:21)
<asynchronous suspension>
#68     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:97:43)
<asynchronous suspension>
#69     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1218:71)
<asynchronous suspension>
#70     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#71     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183:20)
<asynchronous suspension>
#72     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:989:23)
<asynchronous suspension>
#73     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1889:24)
<asynchronous suspension>
#74     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
#75     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395:29)
#76     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#77     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#78     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:19)
#79     _rootRun (dart:async/zone.dart:1126)
#80     _CustomZone.run (dart:async/zone.dart:1023)
#81     runZoned (dart:async/zone.dart:1501)
#82     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484:12)
#83     Driver.start (package:analysis_server/src/server/driver.dart:443:5)
#84     main (file:///M:/Coding/Applications/Google/dart-sdk/sdk/pkg/analysis_server/bin/server.dart:12:11)
#85     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#86     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\devicelab",
        "explicitFileCount": 86,
        "implicitFileCount": 805,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\bad_path",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\bad_import",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\asset_test\\font",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\syntax_error",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\changed_sdk_location",
        "explicitFileCount": 1,
        "implicitFileCount": 93,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\asci_casing",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\asset_test\\main",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\bad_package",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\examples\\flutter_gallery",
        "explicitFileCount": 91,
        "implicitFileCount": 1033,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools",
        "explicitFileCount": 197,
        "implicitFileCount": 1536,
        "workItemQueueLength": 142,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\good",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by a14n** [comment]
Already fixed by #918 . You shouldn't hit the issue with 0.1.44

**Comment by DanTup** [comment]
Aha, cool; thanks!

**Comment by pq** [comment]
Optimistically closing.  Please re-open if needed.

PS: late thanks for the report!
