### ISSUE TITLE
Add lint warning about recommended import style

### ISSUE THREAD

**Issue by Rockvole** [dart-lang/linter#987]
I have some code which confused me for a while.

main.dart
<code>import 'package:kbml_viewer/globals.dart';</code>
<code>import 'preferences/preferences_description_list.dart';</code>

preferences_description_list.dart
<code>import '../globals.dart';</code>

The main page displays the preferences_description_list (a list of descriptions).
The main page, has a preferences page button and that preferences page also displays a variant of the same list (e.g. can also delete items from the list).

When displaying the list from the main page I get an error :

    E/flutter ( 3086): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    E/flutter ( 3086): FileSystemException: Directory listing failed, path = 'null/keyboards/' (OS Error: No such file or directory, errno = 2)
    E/flutter ( 3086): #0      FileTools.directoriesInDirectory (package:keyboard/src/file_tools.dart:21:5)
    E/flutter ( 3086): <asynchronous suspension>
    E/flutter ( 3086): #1      _PreferencesDescriptionsState._onRefresh (package:kbml_viewer/preferences/preferences_description_list.dart:47:42)
    E/flutter ( 3086): <asynchronous suspension>
    E/flutter ( 3086): #2      _PreferencesDescriptionsState.initState (package:kbml_viewer/preferences/preferences_description_list.dart:72:5)
    E/flutter ( 3086): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3743:58)
    E/flutter ( 3086): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
    E/flutter ( 3086): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
    E/flutter ( 3086): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
    E/flutter ( 3086): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
    E/flutter ( 3086): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
    E/flutter ( 3086): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
    E/flutter ( 3086): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
    E/flutter ( 3086): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
    E/flutter ( 3086): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
    E/flutter ( 3086): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
    E/flutter ( 3086): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
    E/flutter ( 3086): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
    E/flutter ( 3086): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
    E/flutter ( 3086): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
    E/flutter ( 3086): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
    E/flutter ( 3086): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
    E/flutter ( 3086): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
    E/flutter ( 3086): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
    E/flutter ( 3086): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
    E/flutter ( 3086): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
    E/flutter ( 3086): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
    E/flutter ( 3086): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
    E/flutter ( 3086): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
    E/flutter ( 3086): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
    E/flutter ( 3086): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
    E/flutter ( 3086): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
    E/flutter ( 3086): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
    E/flutter ( 3086): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
    E/flutter ( 3086): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
    E/flutter ( 3086): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
    E/flutter ( 3086): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
    E/flutter ( 3086): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
    E/flutter ( 3086): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
    E/flutter ( 3086): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
    E/flutter ( 3086): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
    E/flutter ( 3086): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
    E/flutter ( 3086): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
    E/flutter ( 3086): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
    E/flutter ( 3086): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
    E/flutter ( 3086): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framewor
    E/flutter ( 3086): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    E/flutter ( 3086): FileSystemException: Directory listing failed, path = 'null/keyboards/' (OS Error: No such file or directory, errno = 2)
    E/flutter ( 3086): #0      FileTools.directoriesInDirectory (package:keyboard/src/file_tools.dart:21:5)
    E/flutter ( 3086): <asynchronous suspension>
    E/flutter ( 3086): #1      _PreferencesDescriptionsState._onRefresh (package:kbml_viewer/preferences/preferences_description_list.dart:47:42)
    E/flutter ( 3086): <asynchronous suspension>
    E/flutter ( 3086): #2      RefreshIndicatorState._show.<anonymous closure> (package:flutter/src/material/refresh_indicator.dart:338:53)
    E/flutter ( 3086): #3      _RootZone.runUnary (dart:async/zone.dart:1381:54)
    E/flutter ( 3086): #4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
    E/flutter ( 3086): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637:45)
    E/flutter ( 3086): #6      Future._propagateToListeners (dart:async/future_impl.dart:666:32)
    E/flutter ( 3086): #7      Future._completeWithValue (dart:async/future_impl.dart:481:5)
    E/flutter ( 3086): #8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:511:7)
    E/flutter ( 3086): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    E/flutter ( 3086): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

When I display the list from the preferences page it works just fine. It confused me for a while since I am new to dart I thought I didnt write the singleton correctly.

I can fix the error, by either changing to :
<code>import 'package:kbml_viewer/preferences/preferences_description_list.dart';</code>
in the main page, or :
<code>import 'package:kbml_viewer/globals.dart';</code>

I realise I should not be mixing styles, but for beginners it would be nice to get some advice on the best style.

**Comment by pq** [comment]
This has come up a bunch.  Thanks for the report!

cc @bwilkerson

**Comment by bwilkerson** [comment]
The most critical piece is that you be consistent when a library inside `lib` imports another library within `lib`. You can either _always_ use `package:` URIs or you can _always_ use relative paths. Either will work as far as Dart is concerned. If you want to minimize the issues you see when using the analyzer, then I recommend using `package:` everywhere.

**Comment by bwilkerson** [comment]
Unfortunately, relative imports are required when a library outside of `lib` needs to import another library outside of `lib` (such as a test importing test support code).

**Comment by pq** [comment]
In light of that, how about a rule that flags all relative imports to files in `lib`?

**Comment by zoechi** [comment]
related #33076

**Comment by MisterJimson** [comment]
Any progress or more thoughts on this? I would really like a lint to only allow package imports in /lib.
